### ISSUE TITLE
Implementando Socket.io en Vue

### ISSUE THREAD

**Issue by dalailomo** [VueJS-Barcelona/talks#11]
# Vue + Vuex + Socket.io

# Descripción

En esta charla os mostraremos como integrar [Socket.io](https://socket.io/) en un proyecto con [Vue](https://vuejs.org/) y [Vuex](https://vuex.vuejs.org/).

Socket.io es una librería que nos permite poder desarrollar aplicaciones manejando eventos en tiempo real (a q mola? 😸).

# Bio del Ponente

Mi nombre es Pedro Sánchez y actualmente estoy trabajando como Front End developer en Tokiota.

# Nivel

M

(S - Beginner, M - Intermediate, L- Advanced)
(S - Iniciación, M - Intermedio, L - Avanzado)

# Duración

~30 minutos

**Comment by xavism** [comment]
you da best ma friend!
