### ISSUE TITLE
Vue server side rendering

### ISSUE THREAD

**Issue by L3bowski** [VueJS-Barcelona/talks#13]
# Vue server side rendering

Walk-through the process of transforming a 2.X vue-cli scaffolded Vue app into a SEO compliant blazing fast server rendered app. We will meet the main problems when dealing with ssr and we will discover possible ways to solve them.

## About me

My name is Carles Capellas, I am 25 years old and I am passionate about software, specially JavaScript. I enjoy building web apps and learning new ways of doing web development simpler 😎 Find out more about me in [my personal website](http://carlescapellas.xyz/)! (of course made in Vue)

**Comment by xavism** [comment]
Thx mate!
