### ISSUE TITLE
Extend Vue CLI 3.0 to meet your project needs

### ISSUE THREAD

**Issue by Djangoum** [VueJS-Barcelona/talks#15]
# Title / Título
Extend Vue CLI 3.0 to meet your project needs

# Description / Descripción
We will look at vue cli 3.0 plugin architecture and make a little demo about how we can develop diferent plugins to meet some needs of our project, also integrating the new and fresh vue cli 3.0 UI 👍 

# Speaker Bio / Bio del Ponente
Software developer at Roche.

# Level / Nivel

M - Intermedieate
# Duration / Duración
30 min

**Comment by xavism** [comment]
Yasss!
