### ISSUE TITLE
Nuxt: the framework to scale up universal Vue apps

### ISSUE THREAD

**Issue by afontcu** [VueJS-Barcelona/talks#16]
# Title / Título

Nuxt: the framework to scale up universal Vue apps.

# Description / Descripción

Nuxt is the number 1 framework built on top of Vue. It provides tools to create scalable universal applications with ease.

In this talk, we will unveil the benefits of using Nuxt's powerful features, and also discuss the similarities and differences between Nuxt and vue-cli.

# Speaker Bio / Bio del Ponente

I'm [Adrià Fontcuberta](http://fontcuberta.cat), a frontend developer interested in Javascript, CSS, UX, design, agile, product development and everything in between. I help to craft useful, usable and delightful interfaces, applications and experiences.

I currently work as a Senior(?) Frontend Engineer at Holaluz.

# Level / Nivel

S

_(S - Beginner, M - Intermediate, L- Advanced)_

# Duration / Duración

25-30'

**Comment by xavism** [comment]
Yes man!! Thx!
