### ISSUE TITLE
A walk through Vuejs testing with Jest, Cypress and Cucumber

### ISSUE THREAD

**Issue by condebiel** [VueJS-Barcelona/talks#17]
# Title / Título
A walk through Vuejs testing with Jest, Cypress and Cucumber

# Description / Descripción
Diario de abordo de Holaluz sobre testing en Vuejs, donde compartiremos algunas de nuestras experiencias, consejos, buenas prácticas y algún truco. 

# Speaker Bio / Bio del Ponente
Biel Conde, frontend developer con más de 10 años de experiencia, aprendiz de agile coach y fan incondicional de Vuejs en mi día a día. 

Actualmente, trabajando como frontend lead developer en Holaluz.

# Level / Nivel
M

# Duration / Duración
30-40'

**Comment by xavism** [comment]
Thx Biel!!!
