### ISSUE TITLE
Dynamic "hot" 🔥 loading for bundled modules of your Vuejs app using webpack **. (for dummies)

### ISSUE THREAD

**Issue by dalailomo** [VueJS-Barcelona/talks#18]
# Title / Título

Dynamic "hot" 🔥 loading for bundled modules of your Vuejs app using webpack **. (for dummies)

# Description / Descripción

How to dynamically "hot" load already bundled modules of your VueJS application for maximum awesomeness.

# Speaker Bio / Bio del Ponente

I am Pedro S. Casas and I am a frontend developer, currently working at Tokiota.

# Level / Nivel

Intermediate dummies

# Duration / Duración

30 min to 1 hour

**Comment by dalailomo** [comment]
not this time

**Comment by xavism** [comment]
Please, do not call our community members 'dummies'. 
Your comments are not allowed under our conduct code.

Porfavor, vuelva a la legalidad
