### ISSUE TITLE
Make JS great again

### ISSUE THREAD

**Issue by fernandoescolar** [VueJS-Barcelona/talks#2]
# Title / Título
Make JS great again

# Description / Descripción
Breve introducción a Vue.js, haciendo hincapié en las ventajas que aporta sobre otras librerías que resuelven los mismos problemas.

# Speaker Bio / Bio del Ponente
Actualmente estoy trabajando en la empresa Tokiota como consultor. Con una posición de más de 4 palabras. Casi no cabe en la tarjeta de visita. Haciendo que me crea más importante de lo que soy. Llevo programando desde que conozco que se puede programar. No toda la vida, pero sí bastante. También soy coordinador de la comunidad de desarrolladores de .Net de Cataluña CatDotNet. Además de 2015 a 2017 me otorgaron el honor de ser nombrado MVP de Microsoft. Esperemos que no sea la última…

# Level / Nivel
S

# Duration / Duración
20 min.

**Comment by xavism** [comment]
Sin problema @uaalah , las iremos subiendo a este github 🚀
