### ISSUE TITLE
Legacy to Vue

### ISSUE THREAD

**Issue by dfvalero** [VueJS-Barcelona/talks#5]
# Title / Título

Legacy to Vue

# Description / Descripción

Como mover tu legacy (codigo javascript en un .phtml con php, css y javascript todo mezlado) a Vue, teniendo en cuenta dos opciones: refactor con Vuex y sin el.

# Speaker Bio / Bio del Ponente

Actualmente trabajando en La Cúpula Music en Barcelona. He trabajado para varias empresas en Barcelona y Berlin. Mi especialidad es hacer el rediseño de las plataformas en las que he trabajado.

# Level / Nivel

M - Intermediate

# Duration / Duración

40 minutos

**Comment by xavism** [comment]
Hola Buenas! vamos a crear una encuesta con algunas propuestas más para Junio, estarás por Barcelona ese mes?

**Comment by dfvalero** [comment]
Si! Estaré por Barcelona!

**Comment by xavism** [comment]
Hola buenas, estamos montando el siguiente para el 21de Junio. Podrías dar la charla ese dia?

**Comment by dfvalero** [comment]
Si claro!

**Comment by xavism** [comment]
Podrías mejor el 14 de junio? Nos va mejor esa fecha. 😮

**Comment by dfvalero** [comment]
Un poco justo, pero si, ya me espavilo!

**Comment by xavism** [comment]
Perfecto pues puedes marcarte esa fecha, muchas gracias por tu aportación! 😍

**Comment by dfvalero** [comment]
👍

**Comment by xavism** [comment]
Necesitaría tu email y te envio la convocatoria :)

**Comment by dfvalero** [comment]
dfvalero@gmail.com!!

2018-05-28 12:35 GMT+02:00 Xavi Sánchez Mir <notifications@github.com>:
